config/routes.rb
Rails.application.routes.draw do
  resources :users
    root "sessions#new"
    resources :tasks
    resources :sessions
    resources :labels
    namespace :admin do
      resources :users
    end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assosciation.rb
class Assosciation < ApplicationRecord
  belongs_to :task, optional: true
    belongs_to :label, optional: true
end

app/models/label.rb
class Label < ApplicationRecord
  validates :label_type, presence: true, uniqueness:true
    has_many :associations, dependent: :destroy, foreign_key: 'label_id'
    has_many :tasks, through: :associations, source: :task
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  validates :start_date, presence: true
      validates :end_date, presence: true
      validates :status, presence: true
      validates :priority, presence: true , numericality: { only_integer: true, greater_than: -1, less_than: 4 }
      scope :search_status, -> (status){where('status = ?',status)}
      scope :search_title, -> (title){where('title LIKE ?',"%#{title}%")}

      paginates_per 4
      has_many :associations, dependent: :destroy, foreign_key: 'task_id'
      belongs_to :user
      has_many :labels, through: :associations, source: :label
      accepts_nested_attributes_for :associations
    end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence:true, uniqueness:true,length:{maximum: 255}
      validates :username, presence:true, uniqueness:true,length:{maximum: 30}
      before_validation {username.downcase!}
      has_secure_password
      before_destroy :check_if_its_last_admin

      has_many :tasks, dependent: :destroy

      private

      def check_if_its_last_admin
          if self.admin? && User.where(admin: :true).count == 1
              throw :abort
          end
      end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
    before_action :set_label, only: [:show, :edit, :update, :destroy]
    before_action :check_if_admin

    def index
        if logged_in? && current_user.admin?
            @labels = Label.all
        else
            redirect_to new_session_path
        end
    end

    def show
    end

    def new
        @label = Label.new
    end

    def edit
    end

    def create
        @label = Label.new(label_params)
        if @label.save
            redirect_to labels_path, notice: 'Label was successfully created.'
        else
            render :new
        end
    end

    def update
        if @label.update(label_params)
            redirect_to labels_path, notice: 'Label was successfully updated.'
        else
            render :edit
        end
    end

    def destroy
        if @label.destroy
            redirect_to labels_path, notice: 'Label was successfully destroyed.'
        else
            redirect_to labels_path, notice: 'can not delete the label'
        end
    end

    private
    def set_label
        @label = Label.find(params[:id])
    end

    def label_params
        params.require(:label).permit(:label_type)
    end

    def check_if_admin
        if !current_user.admin
            redirect_to new_session_path, notice: "you are not authorized to access this page"
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def index
        render "new"
    end

    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            if user.admin
                redirect_to admin_users_path, notice: 'welcome admin'
            else
                redirect_to tasks_path, notice: 'logged in'
            end
        else
            render "new"
        end
    end

    def destroy
        session.delete(:user_id)
        redirect_to new_session_path
    end
  end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :check_if_logged_in
 before_action :set_task, only: [:show, :edit, :update, :destroy]

 # GET /tasks
 def index
   #if logged_in?
     @search = Task.ransack(params[:q])
     @tasks = @search.result.includes(:associations, :labels).order(created_at: :desc).page(params[:page]).where(user_id: @current_user.id)
     @labels = Label.all
   #else
     redirect_to new_session_path
   end
 end

 # GET /tasks/1
 def show
   @labels = Label.all
 end

 # GET /tasks/new
 def new
   @task = Task.new
   current_user = @current_user
   @labels = Label.all
 end

 # GET /tasks/1/edit
 def edit
   @labels = Label.all
 end

 # POST /tasks
 def create
   @task = Task.new(task_params)
   @labels = Label.all
   if @task.save
     redirect_to @task, notice: 'Task was successfully created.'
   else
     render :new
   end
 end

 # PATCH/PUT /tasks/1
 def update
   if @task.update(task_params)
     redirect_to @task, notice: 'Task was successfully updated.'
   else
     render :edit
   end
 end

 # DELETE /tasks/1
 def destroy
   @task.destroy
   redirect_to tasks_url, notice: 'Task was successfully destroyed.'
 end

 private

 #def check_if_logged_in
   #if !logged_in?
     redirect_to new_task_path, notice: "you are not authorized to access this page"


 # Use callbacks to share common setup or constraints between actions.
 def set_task
   @task = Task.find(params[:id])
 end

 # Only allow a trusted parameter "white list" through.
 def task_params
   params.require(:task).permit(:title,:start_date, :end_date, :status, :priority, :user_id, label_ids: [])
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    if logged_in? && current_user.admin?
      redirect_to admin_users_path
    else
      redirect_to new_session_path
    end
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    #if logged_in?
      redirect_to tasks_path
  #  else
      @user = User.new
    end
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      if logged_in? && current_user.admin
        redirect_to admin_users_path
      else
        session[:user_id] = @user.id
        redirect_to user_path(@user.id), notice: 'User was successfully created.'
      end
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      if current_user.admin
        redirect_to admin_users_path, notice: 'User was successfully updated.'
      else
        redirect_to @user, notice: 'User was successfully updated.'
      end
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: 'User was successfully destroyed.'
    else
      redirect_to admin_users_path, notice: 'can not delete last admin'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:email, :username, :admin,:password, :password_confirmation)
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
         @current_user ||= User.find_by(id: session[:user_id])
     end

     def logged_in?
         current_user.present?
     end
 end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/labels/_form.html.erb
<%= form_with(model: label, local: true) do |form| %>
  <% if label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
      <% label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container d-flex justify-content-center">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Label</h5>
      <div class="field">
        <%= form.label :label_type %>
        <%= form.text_field :label_type %>
      </div>
      <%= form.submit name: "register", class: "btn btn-primary mt-1" %>
    </div>
  </div>
</div>
<% end %>

app/views/labels/edit.html.erb
<h1>Editing Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Show', @label %> |
<%= link_to 'Back', labels_path, class: "btn btn-success ml-5" %>

app/views/labels/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to "Admin dashboard", admin_users_path, class:"btn btn-success ml-2" %>
<div class="nav nav-pills nav-justified">

  <div class="nav-item">
    <% if logged_in? %>
      <%= link_to @current_user.username, user_path(@current_user.id), class:"btn btn-outlined-dark" %>
      <%= link_to "Logout", session_path(@current_user.id), method: :delete, class:"btn btn-dark" %>
    <% else %>
      <% controller.redirect_to new_session_path %>
    <% end %>
  </div>

</div>

<h1>Labels</h1>

<% n=0%>

<table class="table">
  <thead>
    <tr>
      <th>NO</th>
      <th>Label type</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= n += 1 %></td>
        <td><%= label.label_type %></td>
        <td><%= link_to 'Show', label_path(label) %></td>
        <td><%= link_to 'Edit', edit_label_path(label) %></td>
        <td><%= link_to 'Destroy', label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to "Create label", new_label_path, class:"btn btn-primary ml-2" %>

app/views/labels/new.html.erb
<h1>New Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Back', labels_path, class: "btn btn-success ml-5" %>

app/views/labels/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container d-flex justify-content-center">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Label</h5>
      <p class="card-text">
        <strong>Label Type:</strong>
        <%= @label.label_type %>
      </p>
      <%= link_to 'Edit', edit_label_path(@label), class: "btn btn-primary" %>
      <%= link_to 'Back', labels_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lompoeverleaf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, [['Not yet started', 'Not yet started'],['in progress', 'in progress'], ['completed', 'completed']] %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.select :priority, [['high', '1'],['medium', '2'], ['low', '3']] %>
  </div>

  <div class="field_labels">
    <% @labels.each do |labels| %>
    <%= form.check_box :label_ids, { multiple: true, checked: @task.label_ids.include?(label.id), disabled: label[:disabled], include_hidden: false}, label[:id]%>
    <label><%= label.label_type %></label>
    <% end %>
  </div>

  <%= form.hidden_field :user_id, :value => current_user.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<% if logged_in? %>
<% else %>
    <% controller.redirect_to new_session_path %>
<% end %>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<div class="nav nav-pills nav-justified">
  <h1 class="nav-brand ml-2">Tasks</h1>
  <div class="nav-item">
    <% if logged_in? %>
      <%= link_to @current_user.username, user_path(@current_user.id), class:"btn btn-outlined-dark" %>
      <%= link_to "Logout", session_path(@current_user.id), method: :delete, class:"btn btn-dark" %>
    <% else %>
      <% controller.redirect_to new_session_path %>
    <% end %>
  </div>
</div>

<div class="nav nav-pills nav-justified">
  <%= link_to "sort by expiration date", tasks_path(sort_expired: "true"),class:"nav-item"%>
  <%= link_to "sort by priority", tasks_path(sort_priority: "true"),class:"nav-item"%>
    <%= search_form_for @search do |f| %>
      <%= f.label :status_search %>
      <%= f.search_field :status_cont %>
      <%= f.label :title_search %>
      <%= f.search_field :title_cont %>
      <%= f.label :label_search %>
      <%= f.search_field :labels_label_type_cont %>
      <%= f.submit 'search'%>
    <% end %>
</div>

<table class="table mt-3">
  <thead>
    <tr>
      <th>NO</th>
      <th>Title</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Status</th>
      <th>Priority</th>
      <th>Labels</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <% t=0 %>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= t += 1 %></td>
        <td><%= task.title %></td>
        <td><%= task.start_date %></td>
        <td><%= task.end_date %></td>
        <td><%= task.status %></td>
        <%if task.priority.present?%>
          <%if task.priority == 1%>
            <td>high</td>
          <%elsif task.priority == 2%>
            <td>medium</td>
          <%elsif task.priority == 3%>
            <td>low</td>
          <%end%>
        <%end%>
        <%task.labels.each do |label|%>
          <td><%=label.label_type%></td>
        <%end%>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path,class:"mb-2" %>

<%= paginate @tasks, class:"mt-5" %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<% if logged_in? %>
<% else %>
    <% controller.redirect_to new_session_path %>
<% end %>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p id="notice"><%= notice %></p>

<% if logged_in? %>
<% else %>
    <% controller.redirect_to new_session_path %>
<% end %>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @task.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @task.end_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Priority:</strong>
  <%if @task.priority.present?%>
    <%if @task.priority == 1%>
      <span>high</span>
    <%elsif @task.priority == 2%>
      <span>medium</span>
    <%elsif @task.priority == 3%>
      <span>low</span>
    <%end%>
  <%end%>
</p>

<p>
  <strong>Labels:</strong>
  <%@task.labels.each do |label|%>
    <span><%=label.label_type%></span>
  <%end%>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', new_session_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%if @user.id != current_user.id%>
  <%controller.redirect_to tasks_path%>
<%end%>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', tasks_path %>